-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 14:31:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_banco` DEFAULT CHARACTER SET utf8 ;
USE `db_banco` ;

-- -----------------------------------------------------
-- Table `db_banco`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Prestamos` (
  `ID_Prestamo` INT UNSIGNED NOT NULL,
  `Importe_Solicitado` FLOAT NOT NULL,
  `Importe_Intereses` FLOAT NOT NULL,
  `Plazo_Meses` INT NOT NULL,
  `Monto_Mes` FLOAT NOT NULL,
  `Cuotas` INT NOT NULL,
  `DNI` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Prestamo`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Genero` (
  `ID_Genero` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Genero`),
  UNIQUE INDEX `ID_Genero_UNIQUE` (`ID_Genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Nacionalidad` (
  `ID_Nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Provincia` (
  `ID_Provincia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Localidad` (
  `ID_Localidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ID_provincia` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Localidad`),
  INDEX `ID_Provincia_idx` (`ID_provincia` ASC) VISIBLE,
  CONSTRAINT `ID_Provincia`
    FOREIGN KEY (`ID_provincia`)
    REFERENCES `db_banco`.`Provincia` (`ID_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Usuario` (
  `DNI` INT UNSIGNED NOT NULL,
  `CUIL` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `ID_Genero` INT UNSIGNED NOT NULL,
  `ID_Nacionalidad` INT NOT NULL,
  `Fehca_Nac` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `ID_Localidad` INT UNSIGNED NOT NULL,
  `Email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  INDEX `ID_Genero_idx` (`ID_Genero` ASC) VISIBLE,
  INDEX `ID_Nacionalidad_idx` (`ID_Nacionalidad` ASC) VISIBLE,
  INDEX `ID_Localidad_idx` (`ID_Localidad` ASC) VISIBLE,
  CONSTRAINT `ID_Genero`
    FOREIGN KEY (`ID_Genero`)
    REFERENCES `db_banco`.`Genero` (`ID_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Nacionalidad`
    FOREIGN KEY (`ID_Nacionalidad`)
    REFERENCES `db_banco`.`Nacionalidad` (`ID_Nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Localidad`
    FOREIGN KEY (`ID_Localidad`)
    REFERENCES `db_banco`.`Localidad` (`ID_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Usuario_Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Usuario_Banco` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Usuario_DNI` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  INDEX `fk_Usuario_Banco_Usuario1_idx` (`Usuario_DNI` ASC) VISIBLE,
  UNIQUE INDEX `ID_Usuario_UNIQUE` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Banco_Usuario1`
    FOREIGN KEY (`Usuario_DNI`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Telefonos` (
  `Telefono` INT UNSIGNED NOT NULL,
  `Usuario_DNI` INT UNSIGNED NOT NULL,
  INDEX `fk_Telefonos_Usuario1_idx` (`Usuario_DNI` ASC) VISIBLE,
  PRIMARY KEY (`Telefono`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  CONSTRAINT `fk_Telefonos_Usuario1`
    FOREIGN KEY (`Usuario_DNI`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Usuario_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Usuario_Cliente` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Usuario_DNI` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `ID_Usuario_UNIQUE` (`ID_Usuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Cliente_Usuario1_idx` (`Usuario_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_DNI`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Tipo_Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Tipo_Cuenta` (
  `ID_Tipo_Cuenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo_Cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Cuenta` (
  `ID_Cuenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Tipo_Cuenta` INT UNSIGNED NOT NULL,
  `CBU` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `Saldo` FLOAT NOT NULL,
  `Dni_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Cuenta`),
  INDEX `ID_Tipo_Cuenta_idx` (`ID_Tipo_Cuenta` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI_user` ASC) VISIBLE,
  CONSTRAINT `ID_Tipo_Cuenta`
    FOREIGN KEY (`ID_Tipo_Cuenta`)
    REFERENCES `db_banco`.`Tipo_Cuenta` (`ID_Tipo_Cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Dni_user`
    FOREIGN KEY (`Dni_user`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Tipo_Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Tipo_Movimiento` (
  `ID_Tipo_Movimiento` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo_Movimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Movimientos` (
  `ID_Movimiento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Dni_cliente` INT UNSIGNED NOT NULL,
  `ID_Tipo_Movimiento` INT UNSIGNED NOT NULL,
  `Detalle` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID_Movimiento`),
  UNIQUE INDEX `DNI_UNIQUE` (`Dni_cliente` ASC) VISIBLE,
  INDEX `ID_Tipo_Movimiento_idx` (`ID_Tipo_Movimiento` ASC) VISIBLE,
  CONSTRAINT `ID_Tipo_Movimiento`
    FOREIGN KEY (`ID_Tipo_Movimiento`)
    REFERENCES `db_banco`.`Tipo_Movimiento` (`ID_Tipo_Movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Dni_cliente`
    FOREIGN KEY (`Dni_cliente`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco`.`Prestamos` (
  `ID_Prestamo` INT UNSIGNED NOT NULL,
  `Importe_Solicitado` FLOAT NOT NULL,
  `Importe_Intereses` FLOAT NOT NULL,
  `Plazo_Meses` INT NOT NULL,
  `Monto_Mes` FLOAT NOT NULL,
  `Cuotas` INT NOT NULL,
  `DNI` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Prestamo`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `db_banco`.`Usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `db_banco`.`altacuenta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_dni` INT UNSIGNED NOT NULL,
  `tipo_cuenta` INT  UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_dni_UNIQUE` (`user_dni` ASC) VISIBLE,
  CONSTRAINT `user_dni`
    FOREIGN KEY (`user_dni`)
    REFERENCES `db_banco`.`usuario` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_cuenta`
    FOREIGN KEY (`tipo_cuenta`)
    REFERENCES `db_banco`.`tipo_cuenta` (`ID_tipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
  
drop table `db_banco`.`altacuenta`;
  
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
